project_id = "dbltyxypjvbavejkkcer"

[functions.verify-lead-password]
verify_jwt = false

[functions.send-inquiry-confirmation]
verify_jwt = false

[functions.submit-inquiry]
verify_jwt = false

[functions.send-cold-call-interest-email]
verify_jwt = false

[functions.send-quick-send-email]
verify_jwt = false

[functions.delete-all-vehicle-images]
verify_jwt = false

[functions.create-bestellung-api]
verify_jwt = false

[functions.assign-salutations-to-inquiries]
verify_jwt = false